site_name: Starlette Files
site_description: Starlette Files Documentation.

theme:
    name: 'material'

repo_name: accent-starlette/starlette-files
repo_url: https://github.com/accent-starlette/starlette-files
edit_uri: ""

nav:
    - Introduction: 'index.md'
    - Storages: 'storages.md'
    - Handling Files: 'handling_files.md'
    - Handling Images: 'handling_images.md'
    - Image Operations: 'image_operations.md'

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
